### ISSUE TITLE
Enhancement: Thirds additions

### ISSUE THREAD

**Issue by stratacast** [acristoffers/kwin-rectangle#1]
Thank you for making this awesome kwin script of rectangle-style window management! This is exactly what I need for my ultrawide monitor. I was wondering if you would be interested in making another thirds addition. Right now, you can do left, center, and right thirds. Would it be possible to add thirds but with half the vertical space? That way someone could do something like 2 rows by 3 columns

**Comment by acristoffers** [comment]
Hi, nice to know it's useful for more people :)
What you are describing is what I called sixths, if I'm not mistaken.

**Comment by stratacast** [comment]
I'm loving it, thank you for the work on it! And yes you're absolutely right. I misunderstood that when I was looking at it (it makes sense now that you say that). I'm assuming you left gaps between windows for aesthetic? Just wondering, since I noticed that the gaps left from the tiling doesn't work with sticky windows :)

**Comment by acristoffers** [comment]
Yes, I like the gaps, so I decided to put them there. However, they are adjustable. The only problem is that the settings pane only appears if you create a symlink yourself, since the settings panel does not create it. So you can enable it by cloning the repo and using the install script or installing with the settings app and just creating the symlink yourself. Then you can change the outer and inner gaps separately. As I note in the description, I had to disable and reenable the plugin for the changes to take effect (should not be necessary, may be a bug in kwin or something like that).

**Comment by stratacast** [comment]
That works! Thank you. I'll remember to install this from the repo instead of the KDE store
