### ISSUE TITLE
Observations (Bugs?)

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#12]
When a window has been centered with meta + strg + numpad `5` (even when moved afterwards via mouse drag) and then should be moved again with meta + strg + numpad `1`..`4`, `6`..`9` , it maximizes instead of moving.

A window that has been maximized via Rectangle does not show the maximize button in the title bar as 'maximized'. An otherwise maximized window that has been de-maximized via Rectangle does not show the maximize button in the title bar as 'not maximized'.

A ninth (other than center ninth) that has been centered is a few pixels lower than an original center ninth. (Paddings are set to 0, if that is relevant).

Trying to center a (non-center) window on the right (secondary) screen moves it to left (primary) screen, and off-center there.

**Comment by acristoffers** [comment]
> When a window has been centered with meta + strg + numpad `5` (even when moved afterwards via mouse drag) and then should be moved again with meta + strg + numpad `1`..`4`, `6`..`9` , it maximizes instead of moving.

Will be fixed on next release.

> A window that has been maximized via Rectangle does not show the maximize button in the title bar as 'maximized'. An otherwise maximized window that has been de-maximized via Rectangle does not show the maximize button in the title bar as 'not maximized'.

Will be fixed on next release. Note however that the Maximized state of the window will only be turned off, never on, as it has different meanings for kwin-rectangle and kwin itself. To truly maximize (and to minimize) just use kwin built-ins.

> A ninth (other than center ninth) that has been centered is a few pixels lower than an original center ninth. (Paddings are set to 0, if that is relevant).

That's because the centering is done by calculating the x,y coordinate that centers the window on the screen ignoring margins and the center ninth is calculated differently. For me the difference is only a few pixels, which points towards rounding error. However, you seem to have another problem:

> Trying to center a (non-center) window on the right (secondary) screen moves it to left (primary) screen, and off-center there.

There's a note in the README about something similar to this, related to the way Plasma handles multiple monitors. Please take a look there to see if that's not the problem you are facing.

**Comment by noyannus** [comment]
Thanks for fixing!

The little jerk when centering is not really an issue, merely an observation. 

The centering on the other screen happens also when the mouse is over the active window, and with these settings:

![2023-04-22_13-04-54](https://user-images.githubusercontent.com/6339921/233781422-4d4d7433-45b6-4705-a6a6-a6d044fb66f3.png)

**Comment by acristoffers** [comment]
I have an idea why. On it.
