### ISSUE TITLE
Prevent `numlock` with modifiers from toggling number lock possible?

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#14]
The `numlock` key (on number pad) toggles the number lock also when used with modifiers. It would be nice to use it, though, for quarters and fourths (number pad  `numlock`  `  /  `  `  *  `  `  -  `).

Is it possible to not pass on `numlock` in kwin-rectangle? Alternatively, is it possible to send a second `numlock` stroke to toggle back to the previous state?

**Comment by acristoffers** [comment]
It's not possible for me to know, from inside a KWin script, that you pressed a key. The only thing I get is a function call, without any information about what happened to trigger it, so I cannot send another `numlock` (which, in itself, is probably not possible either).

The solution to your problem is probably inside Plasma itself: go to settings -> input methods -> keyboard -> advanced and look for the options with something in the lines of "compatibility options" and inside something like "numeric keyboard always produces digits (like in macOS)". Enable that and your `numlock` toggle problem maybe goes away.

**Comment by noyannus** [comment]
Perfect! Thanks!

Maybe useful to have in the Readme?
