### ISSUE TITLE
Weird behaviour when combined with `Window to Next Screen`

### ISSUE THREAD

**Issue by brendon-at-rea** [acristoffers/kwin-rectangle#7]
Problem: I use two screens, and KDE-rectangle.  If I have a window on Screen 0, and use Meta-Shift-Right to move the `Window to Next Screen` (this successfully moves the window to Screen 1), followed by eg Meta-Ctrl-Right to use `Rectangle Halves: Right`, the window will 
- move back to screen0
- fill the right half of the screen

Expected behaviour:  `Rectangle Halves: Right` should leave the window on Screen 1, and fill the right half of the screen.

Discussion: This might be a bug in the other kwin scripts, possibly `Window to Next Screen` hasn't updated something, leaving the window believing it is still on Screen 0 even though I can see it on Screen 1.

If I move the window from screen 0 to screen 1 using the mouse, and then use `Rectangle Halves: Right`, then I don't see this behaviour.

**Comment by acristoffers** [comment]
When using any shortcut, the window will follow the mouse (it's a kwin problem, sorta). No matter how you move the window, it will tile where the mouse is. Can you test this to see if we got the same weird behaviour? If it is the case I can try to find a way to figure the dimensions of the monitor the window is actually in, but I'm not sure it's possible. I have some incomplete memory of looking this up, but I'm not sure if I already tried or if it's just a déjà-vu.

**Comment by brendon-at-rea** [comment]
Yes!   The window tiles where the mouse is!    That makes sense, and I can work with that.

Feel free to close this if you want. It would be better for the window to stay on the screen where it is, but this behaviour is ok.

By the way, thanks for this great tool!

**Comment by acristoffers** [comment]
I'm glad to know you like it ^^

I'll see if I can find a way to make it work better this weekend, but don't get your hopes high: kwin's documentation is a bit lacking and confusing, I had to read other's people code to understand how it works and to find the necessary functions. But I'll try.

**Comment by acristoffers** [comment]
Ok, I'll close it as "won't fix" because I found an option in the settings application that change this behavior, so I'll prefer to honor the user choice: go to settings -> Window Management -> Window Behaviour -> Focus -> Multiscreen behaviour. I'm on 5.27 and have the following options:

![image](https://user-images.githubusercontent.com/2191364/219873187-e19253e6-d03c-417b-9c6e-752bd62412ff.png)

If you deselect "active screen follows mouse", the window won't follow the mouse to another desktop, and will tile itself inside it's current desktop/monitor. The "separate screen focus" plays no role in it. So you can change it there.

Feel free to reopen the issue if you think this is not a good solution.

Thanks for the feedback, it's always appreciated.
