### ISSUE TITLE
[Enhancement] More possibilities for layouts

### ISSUE THREAD

**Issue by noyannus** [acristoffers/kwin-rectangle#9]
On a full keyboard, can the numeric keypad, navigation keys, and cursor control keys be fully used, possibly with multiple (non-modifier) keys pressed together? 

That would mean making all these keys reactive (currently, at least the number pad 5 is finicky [on a Microsoft Natural 4000]).

And to have more than one key pressed would allow for very flexible layouts. Let me explain with an example, where key position matches screen position of window. We could send a window to any of the 1/6 screens with `meta +`
```
|  ins  | home | pgup |
|---------------------|
|  del  | end  | pgdn |
```
and have an easy mnemonic to boot. 

Combining two keys would give us 2/6 screens. Example window positions for `meta +`
```
|  ins  + home | pgup |
|--------------|  +   |
|  del  + end  | pgdn |
```

A fully working number pad would allow to set windows (using different combinations of modifiers) to
- screen quarters (7, 9, 3, 1 for NW, NE, SE, SW) and halves (8, 6, 2, 4 for top, right, bottom, left),
- screen ninths (1 thru 9),
- centered, in various sizes (5, with various combinations of modifiers).
- minimized (0), or maximized (enter).

With more than one number pressed, any adjacent ninths that form a rectangle could combine into a position/size of their own.

Finally, with again a different modifier combination, the number pad could be set to stepwise moves in 8 directions (1 thru 9, except 5).

As a nice side effect, the above together would free the arrow keys to be used for something else, e.g., shifting virtual desktops, volume control, ...

One can dream, can't one?

**Comment by acristoffers** [comment]
The keyboard shortcuts are managed by KWin itself, I only tell it to call me back when a certain key combination is pressed. If you try to register two non-modifier keys within System Settings you can see that it does not let you, so unfortunately I cannot register it either. The idea is great, though.

For the second part:
-  you can just change the shortcuts in System Settings to use modifier+number for the existing ones.
- We don't have ninths because it would be too small, but if you have a use case for it, it is not that hard to implement. 
- Centering with a predefined size is also easy to implement.
- KWin already has minimize/maximize commands and I already give a maximize that respects the padding setting.

For the third part, that may be implementable. I didn't think about it because I don't use the numpad, it's too far away from the homerow for me, and I have a numpad-less keyboard, but I can see your point.

A lot of what you want is possible by just adjusting the shortcuts in system settings, but unfortunately the coolest idea is impossible (at least for now) because of the way Plasma itself works. I'll refactor the code and insert the ninths more centering options, and maybe the stepwise movement, but this last one is not a promise, I want to think better about how to do it because it requires saving state or somehow recognizing where the window is.

**Comment by acristoffers** [comment]
Version 1.2.4 has ninths and the possibility to move the window to adjacent spaces in the grid.

**Comment by noyannus** [comment]
Wow, that was fast! Thanks for the ninths!

The use case for them is every large monitor, especially when the ninths are used together with thirds and sixths. 

Hypothetical example, journalist: top-left sixth = web research, bottom-left sixth = image collection, middle third = article composing, top-right ninth = live feed or recording of covered event or interview, middle-right ninth = chat, bottom-right ninth = baby cam.

Too bad that KWin won't play nice with multiple non-modifiers. Maybe, some day...

I've tried to fathom the new possibilities and built a set of settings for extensive numpad use that already feels very natural. Also found bugs and had an idea for a naming scheme. I'll post them in different issues to keep them separate. 

Have a nice holiday!

**Comment by acristoffers** [comment]
You're welcome.
